#!/bin/bash

#color control codes to highlight console output
red=`tput setaf 1`
reset=`tput sgr0`

REAL_FILE=$(readlink $0 || echo $0)
BASE_DIR=$(dirname $(dirname $REAL_FILE))

export BUNDLE_GEMFILE="$BASE_DIR/Gemfile"
#DO NOT CHANGE VARIABLE NAME: RBENV_VERSION. It is needed to run ruby version manager rbenv.
export RBENV_VERSION=$(cat $BASE_DIR/.ruby-version)

if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]]; then
    source "/usr/local/rvm/scripts/rvm"
elif [[ -s "/usr/local/opt/asdf/asdf.sh" ]]; then
    source "/usr/local/opt/asdf/asdf.sh"
elif [[ -s "/usr/local/share/chruby/chruby.sh" ]]; then
    source "/usr/local/share/chruby/chruby.sh"
fi

eval "$COMMAND" > /dev/null

exec ruby -I "$BASE_DIR/lib" -r ticker/boot -e boot_ticker $@
